version: 2.1

executors:
  ubuntu-build:
    description: "A regular build executor based on ubuntu image"
    docker:
      - image: envoyproxy/envoy-build:faea2a2ebc397b7a3a5e3c877ceaefc5cf4daf25
    resource_class: xlarge
    working_directory: /source

jobs:
   release:
     executor: ubuntu-build
     steps:
       - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
       - checkout
       - run: ci/do_circle_ci.sh bazel.release
       - setup_remote_docker
       - run: ci/docker_push.sh
       - run: ci/docker_tag.sh
   asan:
     executor: ubuntu-build
     steps:
       - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
       - run: echo $CIRCLE_SHA1
       - run: echo $CIRCLE_PR_NUMBER
       - run: curl https://api.github.com/repos/envoyproxy/envoy/pulls/$CIRCLE_PR_NUMBER/commits
       - checkout
       - run: ci/do_circle_ci.sh bazel.asan
   tsan:
     executor: ubuntu-build
     steps:
       - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
       - checkout
       - run: ci/do_circle_ci.sh bazel.tsan
   api:
     executor: ubuntu-build
     steps:
       - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
       - checkout
       - run: ci/do_circle_ci.sh bazel.api
       - add_ssh_keys:
           fingerprints:
             - "fb:f3:fe:be:1c:b2:ec:b6:25:f9:7b:a6:87:54:02:8c"
       - run: ci/api_mirror.sh
   filter_example_mirror:
     executor: ubuntu-build
     steps:
       - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
       - checkout
       - add_ssh_keys:
           fingerprints:
             - "f6:f9:df:90:9c:4b:5f:9c:f4:69:fd:42:94:ff:88:24"
       - run: ci/filter_example_mirror.sh
   ipv6_tests:
     machine: true
     steps:
     - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
     - checkout
     - run:
         name: enable ipv6
         command: |
           echo '{
             "ipv6": true,
             "fixed-cidr-v6": "2001:db8:1::/64"
           }' | sudo tee /etc/docker/daemon.json

           sudo service docker restart
     - run: dig go.googlesource.com A go.googlesource.com AAAA # Debug IPv6 network issues
     - run: ifconfig
     - run: route -A inet -A inet6
     - run: curl -v https://go.googlesource.com
     - run: curl -6 -v https://go.googlesource.com || true
     - run: ./ci/do_circle_ci_ipv6_tests.sh

   coverage:
     executor: ubuntu-build
     steps:
       - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
       - checkout
       - run: ci/do_circle_ci.sh bazel.coverage
       - run: ci/coverage_publish.sh
       - store_artifacts:
           path: /build/envoy/generated/coverage
   format:
     executor: ubuntu-build
     resource_class: small
     steps:
       - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
       - checkout
       - run: ci/do_circle_ci.sh check_format
       - run: ci/do_circle_ci.sh check_spelling
   build_image:
     docker:
       - image: circleci/python:2.7
         environment:
           # See comment in do_circle_ci.sh for why we do this.
           NUM_CPUS: 8
     resource_class: xlarge
     steps:
       - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
       - checkout
       - setup_remote_docker
       - run: ci/build_container/docker_push.sh
   docs:
     executor: ubuntu-build
     steps:
       - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
       - checkout
       - run: ci/do_circle_ci.sh docs
       - add_ssh_keys:
           fingerprints:
             - "44:c7:a1:9e:f4:9e:a5:33:11:f1:0e:79:e1:55:c9:04"
       - run: docs/publish.sh
       - store_artifacts:
           path: generated/docs
   mac:
     macos:
       xcode: "9.3.0"
     steps:
       - run: sudo ntpdate -vu time.apple.com
       - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
       - checkout
       - run: ci/mac_ci_setup.sh
       - run: ci/mac_ci_steps.sh

workflows:
  version: 2
  all:
    jobs:
      - release:
          filters:
            tags:
              only: /^v.*/
      - asan
      - tsan
      - api
      - filter_example_mirror
      - ipv6_tests
      - coverage
      - format
      - build_image
      - docs:
          filters:
            tags:
              only: /^v.*/
      - mac
